"""add_product_units_and_float_quantities

Revision ID: 708b348cb7c9
Revises: 038dfe1a0cb6
Create Date: 2026-01-17 14:23:19.865188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '708b348cb7c9'
down_revision: Union[str, None] = '038dfe1a0cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_users_profile_clerk_user_id', table_name='users_profile')
    # op.drop_table('users_profile')
    op.alter_column('inventory', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    
    # Create Enum types
    unittype = sa.Enum('piece', 'volume', name='unittype')
    unittype.create(op.get_bind())
    
    unitlabel = sa.Enum('pcs', 'L', 'ml', name='unitlabel')
    unitlabel.create(op.get_bind())

    op.add_column('products', sa.Column('unit_type', unittype, nullable=False, server_default='piece'))
    op.add_column('products', sa.Column('unit_label', unitlabel, nullable=False, server_default='pcs'))
    op.alter_column('stock_logs', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('stock_logs', 'previous_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('stock_logs', 'new_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_logs', 'new_quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('stock_logs', 'previous_quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('stock_logs', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'unit_label')
    op.drop_column('products', 'unit_type')
    
    sa.Enum(name='unitlabel').drop(op.get_bind())
    sa.Enum(name='unittype').drop(op.get_bind())
    op.alter_column('inventory', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('users_profile',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clerk_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarding_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_profile_pkey')
    )
    op.create_index('ix_users_profile_clerk_user_id', 'users_profile', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###
