"""create_recipes_table

Revision ID: 948deabf67e9
Revises: 708b348cb7c9
Create Date: 2026-01-17 15:41:14.315312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948deabf67e9'
down_revision: Union[str, None] = '708b348cb7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_profile_clerk_user_id', table_name='users_profile')
    op.drop_table('users_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profile',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clerk_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarding_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_profile_pkey')
    )
    op.create_index('ix_users_profile_clerk_user_id', 'users_profile', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###
